### ISSUE TITLE
Allow execution multiple commands in sequence

### ISSUE THREAD

**Issue by jasonkuhrt** [MarcoIeni/glimpse#215]
I have a use case where after toggling the `eslint.enable` setting I need to restart the ESLint LSP otherwise the ESLint squiggly lines are still visible even after toggling off.

Perhaps we can allow arrays to be passed to `command`?

**Comment by MarcoIeni** [comment]
This should be possible already
https://github.com/MarcoIeni/glimpse/blob/51d2a44e1a47d03e72287bd906d352b7f2526952/src/keys/files.ts#L10

**Comment by jasonkuhrt** [comment]
So it seems to not work with array from 🤔 

![CleanShot 2023-11-20 at 14 26 20@2x](https://github.com/MarcoIeni/glimpse/assets/284476/c39747ea-4ec3-4814-924d-35961fd57420)

**Comment by MarcoIeni** [comment]
It's `commands`, not `command`.
But maybe this was a wrong design decision 😅

**Comment by jasonkuhrt** [comment]
Ah!

I think having config in TS instead of JS would go a long way to helping here ;) 

I would like to contribute toward that but not sure when.

Allowing to pass an array to `command` (non plural) might be best. Having both `commands` and `command` seems a little confusing since it then makes possible to have both keys, which is strange?

**Comment by MarcoIeni** [comment]
> I think having config in TS instead of JS would go a long way to helping here

Is it feasible? If yes, can you open an issue with the instructions on how to achieve it?

> Allowing to pass an array to command (non plural) might be best.

Yeah, agree. Not sure why I took this weird design decision 😅 opened https://github.com/MarcoIeni/glimpse/issues/222
